pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('mern-jenkins-app') {
                    sh '/usr/bin/npm run install:all'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('mern-jenkins-app') {
                    sh '/usr/bin/npm run test'
                }
            }
        }

        stage('Build Client') {
            steps {
                dir('mern-jenkins-app') {
                    sh '/usr/bin/npm run build'
                }
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: 'mern-jenkins-app/client/dist/**', fingerprint: true
        }
    }
}
